/*
 * generated by Xtext
 */
package org.xtext.de.htwg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PluginUiModule extends org.xtext.de.htwg.ui.AbstractPluginUiModule {
	public PluginUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
