/**
 * generated by Xtext
 */
package org.xtext.de.htwg.ui.contentassist;

import org.xtext.de.htwg.ui.contentassist.AbstractPluginProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PluginProposalProvider extends AbstractPluginProposalProvider {
}
