/**
 * generated by Xtext
 */
package org.xtext.de.htwg.validation;

import org.xtext.de.htwg.validation.AbstractPluginValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PluginValidator extends AbstractPluginValidator {
}
