/*
* generated by Xtext
*/
package org.xtext.de.htwg;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PluginStandaloneSetup extends PluginStandaloneSetupGenerated{

	public static void doSetup() {
		new PluginStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

