/*
 * generated by Xtext
 */
package org.xtext.de.htwg;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PluginRuntimeModule extends org.xtext.de.htwg.AbstractPluginRuntimeModule {

}
